//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalifaxScienceLibrary_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class buy_items
    {
        public int trn_code { get; set; }
        public long C_id { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual item item { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
