//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalifaxScienceLibrary_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthly_expense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public monthly_expense()
        {
            this.mothlyexpense_employee = new HashSet<mothlyexpense_employee>();
        }
    
        public int monthlyExpense_id { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public Nullable<decimal> cost_heat { get; set; }
        public Nullable<decimal> cost_water { get; set; }
        public Nullable<decimal> cost_electricity { get; set; }
        public Nullable<int> rent_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mothlyexpense_employee> mothlyexpense_employee { get; set; }
        public virtual rent rent { get; set; }
    }
}
