//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalifaxScienceLibrary_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class mothlyexpense_employee
    {
        public Nullable<decimal> hours_worked { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string SIN { get; set; }
        public int monthlyExpense_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual monthly_expense monthly_expense { get; set; }
    }
}
