//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalifaxScienceLibrary_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rent()
        {
            this.monthly_expense = new HashSet<monthly_expense>();
        }
    
        public int rent_id { get; set; }
        public string year { get; set; }
        public Nullable<decimal> cost_rent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<monthly_expense> monthly_expense { get; set; }
    }
}
